### ISSUE TITLE
Connection-String to env

### ISSUE THREAD

**Issue by Cahllagerfeld** [kaiwalyakoparkar/practice-node-applications#2]
[here](https://github.com/kaiwalyakoparkar/practice-node-applications/blob/1564e6b730b2f0b5649896480875e94493aade42/routes/server.js#L14) your connection-string for mongo is hard-coded. I'd put this to your `.env`

**Comment by kaiwalyakoparkar** [comment]
Thanks for pointing out! I will do that soon!

**Comment by Cahllagerfeld** [comment]
I can PR when I'm back at home, or do you want to do that

**Comment by kaiwalyakoparkar** [comment]
Both ways would work. Actually, my exam tenure is going on so not getting enough time to look into it :)
